const routes = {
  AUTH_STACK: 'AUTH_STACK',
  AUTH: {
    AUTH: 'AUTH',
    LOGIN: 'LOGIN',
    SIGN_UP: 'SIGN_UP',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    RESET_PASSWORD: 'RESET_PASSWORDL',
  },
  MAIN_STACK: 'MAIN_STACK',
  MAIN: {
    MAIN_DRAWER: 'MAIN_DRAWER',
    DASHBOARD: 'DASHBOARD',
    MAIN: 'MAIN',
    HOME: 'HOME',
    GAME: {
      FLAPPY_BIRD: 'FLAPPY_BIRD',
    },
    VOUCHER: 'VOUCHER',
    LOCATION: 'LOCATION',
    PROFILE: 'PROFILE',
  },
};
export default routes;
